2024-08-16 00:38:13,563 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-08-16 00:38:13,572 - httpx - DEBUG - load_ssl_context verify=True cert=None trust_env=True http2=False
2024-08-16 00:38:13,572 - httpx - DEBUG - load_verify_locations cafile='/Users/haunter/Library/Python/3.9/lib/python/site-packages/certifi/cacert.pem'
2024-08-16 00:38:13,586 - discord.client - DEBUG - on_ready has successfully been registered as an event
2024-08-16 00:38:13,587 - discord.client - DEBUG - on_message has successfully been registered as an event
2024-08-16 00:38:13,587 - asyncio - DEBUG - Using selector: KqueueSelector
2024-08-16 00:38:13,587 - discord.client - INFO - logging in using static token
2024-08-16 00:38:14,400 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: 125ac39c41ca58a5fb319c06682ee236).
2024-08-16 00:38:16,402 - root - INFO - Logged in as ChatGPT#2655
2024-08-16 00:38:31,423 - root - DEBUG - Received message: !ask are you there? from sabrinas.haunter (ID: 803019971377889280) in channel admin (ID: 1228591709697478716)
2024-08-16 00:38:31,424 - root - DEBUG - User request data saved.
2024-08-16 00:38:31,424 - discord.client - ERROR - Ignoring exception in on_message
Traceback (most recent call last):
  File "/Users/haunter/Library/Python/3.9/lib/python/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/Users/haunter/Desktop/chatgpt_botv2.py", line 148, in on_message
    if active_40kref_channel and message.channel.id == active_40kref_channel:
UnboundLocalError: local variable 'active_40kref_channel' referenced before assignment
2024-08-16 00:45:42,667 INFO Logged in as ChatGPT#2655
2024-08-16 01:11:21,001 INFO Logged in as ChatGPT#2655
2024-08-16 01:14:46,678 INFO Logged in as ChatGPT#2655
2024-08-16 01:15:18,839 ERROR Error during 40kref mode response: Error code: 404 - {'error': {'message': 'The model `gpt-4o-latest` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
2024-08-16 01:17:44,563 INFO Logged in as ChatGPT#2655
2024-08-16 02:17:54,387 INFO Logged in as ChatGPT#2655
2024-08-16 02:18:36,136 INFO Logged in as ChatGPT#2655
2024-08-16 02:19:31,118 ERROR Error during 40kref mode response: 'VectorStores' object has no attribute 'create_and_poll'
2024-08-16 02:26:21,027 INFO Logged in as ChatGPT#2655
2024-08-16 02:27:07,124 ERROR Error during 40kref mode response: 'SyncCursorPage[VectorStoreFile]' object is not subscriptable
2024-08-16 02:37:45,818 INFO Logged in as ChatGPT#2655
2024-08-16 02:38:15,510 ERROR Error during 40kref mode response: create() got an unexpected keyword argument 'tool_resources'
2024-08-16 02:44:03,631 INFO Logged in as ChatGPT#2655
2024-08-16 02:44:22,930 ERROR Error during 40kref mode response: 'VectorStoreFile' object has no attribute 'filename'
2024-08-16 03:00:28,284 INFO Logged in as ChatGPT#2655
2024-08-16 03:02:08,946 ERROR Error during 40kref mode response: 'VectorStoreFile' object has no attribute 'filename'
2024-08-16 03:04:54,379 INFO Logged in as ChatGPT#2655
2024-08-16 03:05:15,342 ERROR Error during 40kref mode response: 'VectorStoreFile' object has no attribute 'file_id'
2024-08-16 03:18:42,106 INFO Logged in as ChatGPT#2655
2024-08-16 03:19:01,229 ERROR Error during 40kref mode response: 'VectorStoreFile' object has no attribute 'file_id'
2024-08-16 03:35:34,644 INFO Logged in as ChatGPT#2655
2024-08-16 03:35:53,307 ERROR Error during 40kref mode response: 'VectorStoreFile' object has no attribute 'filename'
2024-08-16 03:38:02,614 INFO Logged in as ChatGPT#2655
2024-08-16 03:38:20,848 ERROR Error during 40kref mode response: 'VectorStoreFile' object has no attribute 'name'
2024-08-16 03:39:05,548 INFO Logged in as ChatGPT#2655
2024-08-16 03:39:20,437 ERROR Error during 40kref mode response: Error code: 400 - {'error': {'message': "The requested model 'chatgpt-4o-latest' cannot be used with the Assistants API.", 'type': 'invalid_request_error', 'param': 'model', 'code': 'unsupported_model'}}
2024-08-16 03:40:15,848 INFO Logged in as ChatGPT#2655
2024-08-16 03:40:29,152 ERROR Error during 40kref mode response: Error code: 400 - {'error': {'message': "The requested model 'chatgpt-4o-latest' cannot be used with the Assistants API.", 'type': 'invalid_request_error', 'param': 'model', 'code': 'unsupported_model'}}
2024-08-16 03:41:13,148 INFO Logged in as ChatGPT#2655
2024-08-16 03:41:25,235 ERROR Error during 40kref mode response: create() got an unexpected keyword argument 'assistant_id'
2024-08-16 03:42:43,260 INFO Logged in as ChatGPT#2655
2024-08-16 08:18:32,072 INFO Logged in as ChatGPT#2655
2024-08-16 09:50:12,515 ERROR Error during 40kref mode response: create() got an unexpected keyword argument 'assistant_id'
2024-08-16 09:50:20,064 INFO Logged in as ChatGPT#2655
2024-08-16 10:19:55,798 INFO Logged in as ChatGPT#2655
2024-08-16 10:20:26,920 ERROR Error during 40kref mode response: 'async for' requires an object with __aiter__ method, got SyncCursorPage[VectorStoreFile]
2024-08-16 10:26:41,147 INFO Logged in as ChatGPT#2655
2024-08-16 10:27:03,514 ERROR Error during 40kref mode response: object NoneType can't be used in 'await' expression
2024-08-16 10:34:59,886 INFO Logged in as ChatGPT#2655
2024-08-16 10:41:59,726 INFO Logged in as ChatGPT#2655
2024-08-16 10:42:24,562 ERROR Error during 40kref mode response: create() got an unexpected keyword argument 'assistant_id'
2024-08-16 10:49:34,248 INFO Logged in as ChatGPT#2655
2024-08-16 10:49:59,348 ERROR Error during 40kref mode response: create() got an unexpected keyword argument 'tool_resources'
2024-08-16 10:59:16,079 INFO Logged in as ChatGPT#2655
2024-08-16 10:59:41,212 ERROR Error during 40kref mode response: create() got an unexpected keyword argument 'assistant'
2024-08-16 11:14:03,939 INFO Logged in as ChatGPT#2655
2024-08-16 11:14:21,047 ERROR Error during 40kref mode response: local variable 'vector_store_id' referenced before assignment
2024-08-16 11:16:13,445 INFO Logged in as ChatGPT#2655
2024-08-16 11:16:32,087 ERROR Error during 40kref mode response: create() missing 1 required keyword-only argument: 'model'
2024-08-16 11:20:10,048 INFO Logged in as ChatGPT#2655
2024-08-16 11:20:32,316 ERROR Error during 40kref mode response: create() missing 1 required keyword-only argument: 'model'
2024-08-16 11:30:08,851 INFO Logged in as ChatGPT#2655
2024-08-16 11:30:23,378 ERROR Error during 40kref mode response: create() got an unexpected keyword argument 'assistant_id'
2024-08-16 11:31:08,884 INFO Logged in as ChatGPT#2655
2024-08-16 11:31:21,053 ERROR Error during 40kref mode response: local variable 'response' referenced before assignment
2024-08-16 12:54:12,079 ERROR OpenAI API returned an API Error: Error code: 404 - {'error': {'message': 'The model `gpt-4o-latest` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
2024-08-16 13:20:26,413 ERROR Error during DM response: 400 Bad Request (error code: 50035): Invalid Form Body
In content: Must be 2000 or fewer in length.
2024-08-16 14:48:28,387 INFO Logged in as ChatGPT#2655
2024-08-16 14:48:38,212 ERROR Error during 40kref mode response: create() got an unexpected keyword argument 'assistant_id'
2024-08-16 14:49:47,649 INFO Logged in as ChatGPT#2655
2024-08-16 14:52:00,994 ERROR Error during 40kref mode response: create() got an unexpected keyword argument 'assistant_id'
2024-08-16 15:06:13,298 INFO Logged in as ChatGPT#2655
2024-08-16 15:06:50,785 ERROR Error during 40kref mode response: 'Run' object has no attribute 'steps'
2024-08-16 15:10:08,933 INFO Logged in as ChatGPT#2655
2024-08-16 15:10:38,857 ERROR Error during 40kref mode response: 'Run' object has no attribute 'messages'
2024-08-16 15:17:46,576 INFO Logged in as ChatGPT#2655
2024-08-16 15:18:11,968 ERROR Error during 40kref mode response: 'SyncCursorPage[Message]' object is not subscriptable
2024-08-16 15:25:17,444 INFO Logged in as ChatGPT#2655
2024-08-16 15:25:38,806 ERROR Error during 40kref mode response: Error code: 400 - {'error': {'message': "Unknown parameter: 'tools[0].vector_store_ids'.", 'type': 'invalid_request_error', 'param': 'tools[0].vector_store_ids', 'code': 'unknown_parameter'}}
2024-08-16 16:06:28,947 INFO Logged in as ChatGPT#2655
2024-08-16 16:06:48,510 ERROR Error during 40kref mode response: 'SyncPage[FileObject]' object is not subscriptable
2024-08-16 17:13:54,431 ERROR Error during DM response: 400 Bad Request (error code: 50035): Invalid Form Body
In content: Must be 2000 or fewer in length.
2024-08-16 17:36:15,732 INFO Logged in as ChatGPT#2655
2024-08-16 17:36:39,055 ERROR Error during 40kref mode response: 'Run' object has no attribute 'messages'
2024-08-16 17:42:31,372 INFO Logged in as ChatGPT#2655
2024-08-16 17:59:07,953 INFO Logged in as ChatGPT#2655
2024-08-16 18:01:22,506 INFO Logged in as ChatGPT#2655
2024-08-16 18:01:44,065 ERROR Error during 40kref mode response: list index out of range
2024-08-16 18:11:03,664 INFO Logged in as ChatGPT#2655
2024-08-16 18:20:48,062 INFO Logged in as ChatGPT#2655
2024-08-16 18:21:09,546 ERROR Error during 40kref mode response: 'SyncCursorPage[Message]' object is not subscriptable
2024-08-16 18:21:49,842 INFO Logged in as ChatGPT#2655
2024-08-16 19:02:21,014 INFO Logged in as ChatGPT#2655
2024-08-16 19:02:38,119 ERROR Error during 40kref mode response: name 'assistant' is not defined
2024-08-16 22:49:31,430 INFO Logged in as ChatGPT#2655
2024-08-16 22:56:56,460 ERROR Error during 40kref mode response: name 'assistant' is not defined
2024-08-16 23:00:23,128 INFO Logged in as ChatGPT#2655
2024-08-16 23:00:44,204 ERROR Error during 40kref mode response: name 'thread_messages' is not defined
2024-08-16 23:01:49,288 INFO Logged in as ChatGPT#2655
2024-08-16 23:05:15,380 INFO Logged in as ChatGPT#2655
2024-08-16 23:06:33,208 ERROR Error during DM response: 400 Bad Request (error code: 50035): Invalid Form Body
In content: Must be 2000 or fewer in length.
2024-08-16 23:07:04,861 ERROR Error during DM response: 400 Bad Request (error code: 50035): Invalid Form Body
In content: Must be 2000 or fewer in length.
2024-08-16 23:47:59,211 ERROR OpenAI API returned an API Error: Error code: 404 - {'error': {'message': 'The model `gpt-4o-latest` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
2024-08-16 23:48:35,228 INFO Logged in as ChatGPT#2655
2024-08-17 00:23:31,695 INFO Logged in as ChatGPT#2655
2024-08-17 00:25:19,219 INFO Logged in as ChatGPT#2655
2024-08-17 01:28:38,434 INFO Logged in as ChatGPT#2655
2024-08-17 01:42:12,322 ERROR Error during 40kref mode response: 400 Bad Request (error code: 50035): Invalid Form Body
In content: Must be 2000 or fewer in length.
2024-08-17 01:42:19,650 INFO Logged in as ChatGPT#2655
2024-08-17 08:12:33,124 INFO Logged in as ChatGPT#2655
2024-08-17 08:59:58,449 INFO Logged in as ChatGPT#2655
2024-08-17 09:04:26,706 ERROR Error during 40kref mode response: 'Text' object has no attribute 'replace'
2024-08-17 09:04:44,837 INFO Logged in as ChatGPT#2655
2024-08-17 09:06:22,282 INFO Logged in as ChatGPT#2655
2024-08-17 09:06:53,645 INFO Logged in as ChatGPT#2655
2024-08-17 09:08:15,524 ERROR Error during 40kref mode response: 'Text' object has no attribute 'replace'
2024-08-17 09:09:11,300 INFO Logged in as ChatGPT#2655
2024-08-17 09:10:17,378 INFO Logged in as ChatGPT#2655
2024-08-17 09:17:22,085 INFO Logged in as ChatGPT#2655
2024-08-17 09:19:38,571 INFO Logged in as ChatGPT#2655
2024-08-17 09:23:26,864 INFO Logged in as ChatGPT#2655
2024-08-17 09:24:02,620 ERROR Error during 40kref mode response: 'Message' object has no attribute 'value'
2024-08-17 09:25:30,259 INFO Logged in as ChatGPT#2655
2024-08-17 09:26:04,994 ERROR Error during 40kref mode response: 'TextContentBlock' object has no attribute 'value'
2024-08-17 09:27:03,013 INFO Logged in as ChatGPT#2655
2024-08-17 09:27:32,524 ERROR Error during 40kref mode response: list index out of range
2024-08-17 09:28:42,912 INFO Logged in as ChatGPT#2655
2024-08-17 09:29:06,265 ERROR Error during 40kref mode response: Error code: 400 - {'error': {'message': "Can't add messages to thread_0ksur71QBwjozphmRn3iZBEl while a run run_Xrygp9w1LyyqCP9jb9o9f9at is active.", 'type': 'invalid_request_error', 'param': None, 'code': None}}
2024-08-17 09:39:02,378 ERROR Error during 40kref mode response: Error code: 400 - {'error': {'message': "Can't add messages to thread_lhkJlR2uhhA8UB4d3MdiM5QL while a run run_K0skkpVCjO5ab8sSYpLtIVzn is active.", 'type': 'invalid_request_error', 'param': None, 'code': None}}
2024-08-17 09:45:36,325 ERROR Error during 40kref mode response: 'BadRequestError' object has no attribute 'http_status'
2024-08-17 09:56:42,855 ERROR Error during assistant mode response: Error code: 400 - {'error': {'message': "Can't add messages to thread_4eXsbZHfoCEeFNABpdCX6EJY while a run run_Khyc3fpsXcWfbAAGUiTI2SJR is active.", 'type': 'invalid_request_error', 'param': None, 'code': None}}
2024-08-17 09:56:42,856 INFO Waiting due to active run error
2024-08-17 09:56:44,967 ERROR Error during assistant mode response: Error code: 400 - {'error': {'message': "Can't add messages to thread_4eXsbZHfoCEeFNABpdCX6EJY while a run run_Khyc3fpsXcWfbAAGUiTI2SJR is active.", 'type': 'invalid_request_error', 'param': None, 'code': None}}
2024-08-17 09:56:44,967 INFO Waiting due to active run error
2024-08-17 09:56:47,082 ERROR Error during assistant mode response: Error code: 400 - {'error': {'message': "Can't add messages to thread_4eXsbZHfoCEeFNABpdCX6EJY while a run run_Khyc3fpsXcWfbAAGUiTI2SJR is active.", 'type': 'invalid_request_error', 'param': None, 'code': None}}
2024-08-17 09:56:47,082 INFO Waiting due to active run error
